### PR TITLE
Extract downloaded files directly into target folder

### PR DESCRIPTION
**Pull request by davidanthoff**
Fixes https://github.com/JuliaLang/juliaup/issues/98.

@simeonschaub could you try whether this fixes it for you?

### CODE REVIEW

**Comment by simeonschaub** [comment]
Yes, `juliaup add` now works for me, awesome! `julialauncher` then always errors for me though:
```
[simeon@majestix juliaup]$ RUST_BACKTRACE=full ./target/debug/julialauncher --help
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/bin/julialauncher.rs:116:68
stack backtrace:
   0:     0x55b09e8a4970 - std::backtrace_rs::backtrace::libunwind::trace::h930cf0be2ce43851
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55b09e8a4970 - std::backtrace_rs::backtrace::trace_unsynchronized::he8c90b95546147bf
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b09e8a4970 - std::sys_common::backtrace::_print_fmt::h2d518076e7529961
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55b09e8a4970 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc03afe5108b924f5
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55b09e8ca17c - core::fmt::write::h03501fd186e1f342
                               at /build/rust/src/rustc-1.54.0-src/library/core/src/fmt/mod.rs:1110:17
   5:     0x55b09e89e145 - std::io::Write::write_fmt::he6bd3203a99cf841
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/io/mod.rs:1588:15
   6:     0x55b09e8a6dfb - std::sys_common::backtrace::_print::h6d8d274cdb4b9345
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55b09e8a6dfb - std::sys_common::backtrace::print::hdbba7107ed5db727
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55b09e8a6dfb - std::panicking::default_hook::{{closure}}::h69616457d96cfc5a
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/panicking.rs:208:50
   9:     0x55b09e8a68d1 - std::panicking::default_hook::h10bbc125f6ee1853
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/panicking.rs:225:9
  10:     0x55b09e8a74d4 - std::panicking::rust_panic_with_hook::h6eb033573a515ade
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/panicking.rs:622:17
  11:     0x55b09e8a6f77 - std::panicking::begin_panic_handler::{{closure}}::hffa4a3da6bf48f5f
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/panicking.rs:517:13
  12:     0x55b09e8a4e6c - std::sys_common::backtrace::__rust_end_short_backtrace::h8245d4af937e663d
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55b09e8a6f09 - rust_begin_unwind
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/panicking.rs:515:5
  14:     0x55b09e591971 - core::panicking::panic_fmt::h497201afa0408fa6
                               at /build/rust/src/rustc-1.54.0-src/library/core/src/panicking.rs:92:14
  15:     0x55b09e5918bd - core::panicking::panic::h37a6fbbdd3c2bfba
                               at /build/rust/src/rustc-1.54.0-src/library/core/src/panicking.rs:50:5
  16:     0x55b09e59573c - core::option::Option<T>::unwrap::h2be2cdf685bfb2ce
                               at /build/rust/src/rustc-1.54.0-src/library/core/src/option.rs:388:21
  17:     0x55b09e5a078d - julialauncher::get_julia_path_from_channel::h31c120107a9b4357
                               at /home/simeon/Documents/Julia/juliaup/src/bin/julialauncher.rs:116:24
  18:     0x55b09e5a17ae - julialauncher::main::h3990965417f2ceb7
                               at /home/simeon/Documents/Julia/juliaup/src/bin/julialauncher.rs:175:36
  19:     0x55b09e5932db - core::ops::function::FnOnce::call_once::haa1cedbd3ebfacec
                               at /build/rust/src/rustc-1.54.0-src/library/core/src/ops/function.rs:227:5
  20:     0x55b09e59676e - std::sys_common::backtrace::__rust_begin_short_backtrace::h63924524edaad058
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/sys_common/backtrace.rs:125:18
  21:     0x55b09e594251 - std::rt::lang_start::{{closure}}::h8fda384d0cac5ef4
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/rt.rs:49:18
  22:     0x55b09e8a79d9 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h23da4485ce9c2fa2
                               at /build/rust/src/rustc-1.54.0-src/library/core/src/ops/function.rs:259:13
  23:     0x55b09e8a79d9 - std::panicking::try::do_call::h26656c7c8049ab32
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/panicking.rs:401:40
  24:     0x55b09e8a79d9 - std::panicking::try::hafa31606aae6b61d
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/panicking.rs:365:19
  25:     0x55b09e8a79d9 - std::panic::catch_unwind::h12fc93c48e24c0bf
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/panic.rs:434:14
  26:     0x55b09e8a79d9 - std::rt::lang_start_internal::hb67ef9ab47b75f78
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/rt.rs:34:21
  27:     0x55b09e594230 - std::rt::lang_start::h9cfbb94077e93590
                               at /build/rust/src/rustc-1.54.0-src/library/std/src/rt.rs:48:5
  28:     0x55b09e5a200c - main
  29:     0x7fbe1b261b25 - __libc_start_main
  30:     0x55b09e59216e - _start
  31:                0x0 - <unknown>
```

**Comment by simeonschaub** [comment]
Sure:
```
[simeon@majestix juliaup]$ cat ~/.julia/juliaup/juliaup.json
{"Default":"release","InstalledVersions":{"1.6.2+0~x64":{"Path":"./julia-1.6.2+0~x64"}},"InstalledChannels":{"1":{"Version":"1.6.2+0~x64"}}}
```

**Comment by davidanthoff** [comment]
Ah, try `juliaup default 1` or `juliaup add release`. This is also due to the faulty initial setup.

**Comment by simeonschaub** [comment]
Ah, that worked!

**Pull request merged**
