### PR TITLE
Update progress bar style to match 1.12 progress bar

### PR DESCRIPTION
**Pull request by christiangnrd**
Couldn't get the smoother version without causing some issues with the colour printing.

I moved the ':' out of the prefix as it was too blue for me but I can revert that if people don't like it.

### CODE REVIEW

**Comment by tecosaur** [comment]
It would be good to use both the left and right half-bar characters.

**Comment by christiangnrd** [comment]
I agree, but I couldn't find how to have the right half-bar character use the alternate colour instead of the main colour. 

image

If there's an easy fix suggested, I'll integrate it with this PR. Otherwise, I suggest we merge this until a more involved solution is implemented.

**Comment by christiangnrd** [comment]
> It would be good to use both the left and right half-bar characters.

**Comment by christiangnrd** [comment]
Didn't mean to close sorry for the spam

**Comment by tecosaur** [comment]
We're using a progress bar library? The only non-trivial component in implementing a progress bar ourselves is the ETA.

**Comment by christiangnrd** [comment]
IMO this should be merged as-is for now as it's still an improvement, and I'll open an issue to improve it so that I can remember to return to it in an unknown amount of time if someone else hasn't gotten to it first.

**Comment by davidanthoff** [comment]
Hm, I have to admit I find that visually way more difficult to distinguish than the existing progress bar... Everything is super small (why is this like two pixels high, only?), the difference in color between "finished" and "in progress" (blue and black) is hard to see... All the default options shown here https://crates.io/crates/indicatif (the progress bar package we use) are _way_ easier on the eye to me...

**Comment by tecosaur** [comment]
Even if it's not visually great to some eyes (I suspect this is a little font-dependent too), I do think there's a fair bit of value in consistency with Pkg.

**Comment by davidanthoff** [comment]
Let's hold this for now, the earliest we should merge this is when 1.12 is actually released.

**Comment by KristofferC** [comment]
I think the bar can be smoothened a bit similar to how it was done in https://github.com/JuliaLang/Pkg.jl/pull/4038.

**Comment by IanButterworth** [comment]
Did that here https://github.com/JuliaLang/juliaup/pull/1287

**Comment by IanButterworth** [comment]
Happy to add the commit here if you agree.

**Comment by christiangnrd** [comment]
Thank you! I don't know when I would have had time to smooth it out

> Happy to add the commit here if you agree.

#1287 includes my commits plus yours so I'll just close this one and the code can be finalized over there

**Pull request closed without merging**
