### PR TITLE
Fixed typo `uopdate`

### PR DESCRIPTION
**Pull request by shayandavoodii**
Found this typo an reported it [here](https://github.com/JuliaLang/juliaup/issues/535#issue-1510343156).

### CODE REVIEW

**Comment by LilithHafner** [comment]
It's best to consolidate multiple related changes like this and #536 into a single commit to the `main` branch by making a single pull request that edits multiple files. I'm going to merge this into #536 to do that.

**Comment by shayandavoodii** [comment]
Surelly it's better to consolidate them, and I would have done it if I knew how that should be settled. I was faced with "Propose change" which led to submitting a PR (as I remember). I will try to merge them now!

**Comment by LilithHafner** [comment]
afaict (as far as I can tell) the web interface only supports conveniently creating PRs that edit a single file through the "propose changes" UI, you would have to make changes locally to make a single commit that edits multiple files without merges.

**Comment by shayandavoodii** [comment]
> you would have to make changes locally to make a single commit that edits multiple files without merges.
You're right. My bad. I should have cloned the repo at first.

**Pull request closed without merging**
