### PR TITLE
feat: support nightly channel

### LINKED ISSUE #96: Add a nightly channel
We'll have to think a bit how we update the version DB for that as we don't want to publish a new version in the store every night... We should probably have a separate version db for nightly builds or something like that, so that we can insulate users that don't deal with that from frequent updates of that. We also need to think about an ID scheme for nightly builds. Presumably there is one already? I'm just not familiar with it :)

### PR DESCRIPTION
**Pull request by Roger-luo**
fix #96 

I don't like this implementation but it works...

### CODE REVIEW

**Comment by gdalle** [comment]
This is an awesome feature, thank you!!! Excited for the merge

**Comment by gitboy16** [comment]
Hi, what is blocking this feature to be added? Tks.

**Comment by Roger-luo** [comment]
> Hi, what is blocking this feature to be added? Tks.

I guess @davidanthoff is prob too busy to review this PR, or thinking about something different? I'm not sure...

**Comment by maleadt** [comment]
Pushed some updates:

- squashed, rebased, formatted
- fixed a bug where nightlies got gc'd immediately after update
- removing the target folder before extracting to avoid accumulating files
- only updating nightlies once a day and displaying that in `juliaup status`

How it works:

```
❯ juliaup add nightly
Installing Julia nightly

❯ ls ~/.julia/juliaup
julia-1.10.0+0.x64.linux.gnu/  julia-nightly/  juliaup.json

❯ juliaup status
 Default  Channel  Version                                                Update
---------------------------------------------------------------------------------
       *  1.10     1.10.0+0.x64.linux.gnu
          nightly  nightly (0 days old)

❯ julia +nightly
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.0-DEV.1254 (2024-01-12)
 _/ |\__'_|_|_|\__'_|  |  Commit 0fdd55b163e (0 days old master)
|__/                   |

❯ juliaup update
# does nothing
```

Forcing an update:

```
❯ juliaup status
 Default  Channel  Version                                                Update
---------------------------------------------------------------------------------
       *  1.10     1.10.0+0.x64.linux.gnu
          dev      Linked to `/home/tim/Julia/src/julia/build/dev/julia`
          nightly  nightly (2 days old)

❯ juliaup update
Installing Julia nightly
```

@davidanthoff Could you review? This looks like a pretty good starting point, functionality wise at least. I considered adding support for e.g. `nightly~aarch64`, but that could be a future TODO.

**Comment by StefanKarpinski** [comment]
Will merge some time next week before it gets stale unless there's some feedback to address.

**Comment by davidanthoff** [comment]
Before we move forward with this, can we (at least briefly) revisit a very different design for this. In an ideal world I would much prefer that nightly Julia builds get a version tag (say with the `-alpha`) and are just like any other release. I think that would have many benefits:
- We wouldn't need any special casing in Juliaup.
- One could do bisect things with Juliaup, which I think would be of great benefit.
- It would require (probably?) the Julia release process to be more automated without any human intervention. In my mind that would be a huge plus in general.
- Once we move more towards pinning Julia versions in Manifest.toml files, nightly builds could be pinned like any other build, which also strikes me as really useful.

**Comment by maleadt** [comment]
> In an ideal world I would much prefer that nightly Julia builds get a version tag (say with the `-alpha`) and are just like any other release.

In a way they do (every `-dev` version has a unique version), but I don't think it's realistic to expect that those builds are kept available for people to download. And regardless of whether they are, nightlies are always going to exist too, so it's a useful thing to support in `juliaup`.

That said, I am reworking this PR a little to integrate better with the rest of the `juliaup` codebase in a way that would make such a feature possible in the long run.

**Comment by maleadt** [comment]
OK, did some refactoring and this should be in a better place now. It integrates with the rest of `juliaup`, installing versioned binaries like the other channels do:

```
❯ juliaup add nightly
❯ cat ~/.julia/juliaup/juliaup.json
{
  "InstalledVersions": {
    "1.11.0-DEV.1258-macos-aarch64": {
      "Path": "./julia-1.11.0-DEV.1258-macos-aarch64",
      "LastUpdate": "2024-01-15T12:09:54.486504Z"
    },
  },
  "InstalledChannels": {
    "nightly": {
      "NightlyVersion": "1.11.0-DEV.1258-macos-aarch64"
    },
  },
}
```

The `LastUpdate` field has been added to track then a version was installed, which in the case of a nightly channel is used to determine whether to re-fetch the nightly version (whose URL is unversioned).

I also added support for architecture-specific channels, e.g.:

```
❯ juliaup add nightly~x64
❯ juliaup add nightly~aarch64
[2024-01-15T12:11:58Z DEBUG juliaup::operations] Already installed, skipping

❯ cat ~/.julia/juliaup/juliaup.json
{
  "InstalledVersions": {
    "1.11.0-DEV.1258-macos-aarch64": {
      "Path": "./julia-1.11.0-DEV.1258-macos-aarch64",
      "LastUpdate": "2024-01-15T12:11:58.288328Z"
    },
    "1.10.0+0.aarch64.apple.darwin14": {
      "Path": "./julia-1.10.0+0.aarch64.apple.darwin14",
      "LastUpdate": "2024-01-15T12:09:12.896335Z"
    }
  },
  "InstalledChannels": {
    "nightly": {
      "NightlyVersion": "1.11.0-DEV.1258-macos-aarch64"
    },
    "nightly~x64": {
      "NightlyVersion": "1.11.0-DEV.1263-macos-x86_64"
    },
    "nightly~aarch64": {
      "NightlyVersion": "1.11.0-DEV.1258-macos-aarch64"
    }
  },
}
```

As you can see, this does the expected thing, only using a single version for `nightly`/`nightly~aarch64`, but a different one for `nightly~x64`.

**Comment by StefanKarpinski** [comment]
@davidanthoff, what say you? Can we merge this?

**Comment by maleadt** [comment]
I've been using this actively for a week now, and haven't encountered any issues. Seeing how there have been no technical comments on this change, I propose we merge this.

Even though a different design as suggested in https://github.com/JuliaLang/juliaup/pull/601#issuecomment-1891064633 could have certain advantages, that would require significant changes to the Julia Base CI set-up. Right now, we only have simple nightlies, so I think `juliaup` should support that.

**Comment by gitboy16** [comment]
Thank you @maleadt  for merging this PR.
Would it possible to have new juliaup release so we can test it? Or alternatively if there is a binary file that we can download. (Unfortunetely I cannot build juliaup locally)

**Comment by simsurace** [comment]
Really nice to see this land! +1 for releasing this.

**Comment by davidanthoff** [comment]
Oh, this really should not have been merged at this point. We are in the middle of the test phase of a whole bunch of previous PRs that are quite drastic, and while those changes are making their way through the release-preview channel we should _not_ merge things onto `main`. The window for merging into `main` only opens up again once that build has made it out to the release channel. So that is all entirely irrespective of whether we have agreement that a certain PR should be merged or not, which in this case I also don't think we have.

**Comment by maleadt** [comment]
> while those changes are making their way through the release-preview channel we should _not_ merge things onto `main`

That isn't indicated anywhere.

> So that is all entirely irrespective of whether we have agreement that a certain PR should be merged or not, which in this case I also don't think we have.

I've done my best to address all of the technical issues, but gating this on a very invasive change of non-juliaup infrastructure isn't a realistic ask. All this does is add support for an existing and widely used type of release binary, that isn't going to disappear anytime soon, so I don't see why this needs to be so painful.

**Comment by davidanthoff** [comment]
Alright, I reviewed this now. I'm looking at this assuming that my proposal from above is not viable because it would be too invasive to the existing CI infrastructure.

The primary thing that I don't like with this design is that `juliaup update` is essentially gated behind an update interval for nightly builds. That is quite different from how it works for the other things, where you are guaranteed that a `juliaup update` gets you whatever version exists at that point in time, i.e. the result of that doesn't depend on any throttling. I think there is a fairly simple way to solve this. It does require a minimal change to the Julia CI infrastructure, but my best guess is that is something that could be easily done.

The idea would be that whenever the CI infrastructure uploads a nightly build, it also uploads a text file that contains the version number of the nightly build that it just uploaded. My best guess is that it would be enough to [here](https://github.com/JuliaCI/julia-buildkite/blob/70bde73f6cb17d4381b62236fc2d96b1c7acbba7/utilities/upload_julia.sh#L123) add something like this:
```
if [[ "${BUILDKITE_BRANCH}" == "master" ]]; then
    echo "${JULIA_VERSION}" > NIGHTLYVERSION
   aws s3 cp --acl public-read NIGHTLYVERSION "s3://SOMEAGREEDURL"
fi
```
Note that my bash skills are zero, so I am sure this code snippet doesn't work as is, but could presumably easily be fixed by someone better at that than me :)

At that point we can get rid of the entire update interval thing for nightly. `juliaup update` would just always download that file `NIGHTLYVERSION` when a `nightly` channel is installed, just like it always checks for updates to the version DB. There also wouldn't be a download of an entire nightly tar ball just to check if it is different from the already installed version, all that could be done based on just the version number.

@staticfloat would those changes to the nightly build script be something we could easily do?

--

Another thing we need to handle is an existing linked channel that might be called `nightly`. Right now, if a user has an existing linked channel called `nightly`, then with this PR any code path that attempts to load the config data crashes. That is essentially pretty much anything and includes the self update code for Juliaup itself. So, at that point we couldn't even push out a fix for Juliaup itself anymore, we would have to tell people with that situation to uninstall and manually reinstall. I'm going to merge the revert PR due to this issue.

--

And finally, would be good to have at least some rudimentary test for this.

**Comment by davidanthoff** [comment]
> That isn't indicated anywhere, though.

Fair enough :) So far I've been the only person merging, so I never bothered writing it down. That is clearly not a good situation, I took a first stab [here](https://github.com/JuliaLang/juliaup/wiki/Branch-management).

**Comment by LilithHafner** [comment]
Can we check the hash or last-updated date of the binary instead of a separate version file? That seems like something a reasonable file hosting service would provide.

**Comment by staticfloat** [comment]
Yes, the way we typically check to see if a nightly has updated, is by looking at the headers of an HTTP response, usually `HEAD`:

```
$ curl --HEAD https://julialangnightlies-s3.julialang.org/bin/linux/x86_64/julia-latest-linux-x86_64.tar.gz                   
HTTP/2 200                                                                                                                                             
x-amz-id-2: Jx2TZZZ6Shu6dAe5VmtoraZbQUQEVNNnRXx7uoFQ3kvbNthI88SbMYxFCuS2VANaNJI2S7l2iyc=                                                               
x-amz-request-id: HJYW5GN7ZD9WYCVJ                                                                                                                     
last-modified: Thu, 25 Jan 2024 12:32:32 GMT                                                                                                           
x-amz-expiration: expiry-date="Tue, 26 Mar 2024 00:00:00 GMT", rule-id="Cyberduck-u1YrSIk1"                                                            
etag: "d9e9ebd2c8e25af442b28390a2e5806e-29"                                                                                                            
x-amz-server-side-encryption: AES256                                                                                                                   
content-type: application/x-tar                                                                                                                        
server: AmazonS3                                                                                                                                       
accept-ranges: bytes                                                                                                                                   
age: 10                                                                                                                                                
date: Thu, 25 Jan 2024 16:46:46 GMT                                                                                                                    
via: 1.1 varnish                                                                                                                                       
x-served-by: cache-bfi-krnt7300069-BFI                                                                                                                 
x-cache: MISS                                                                                                                                          
x-cache-hits: 0                                                                                                                                        
x-timer: S1706201196.635083,VS0,VE10614                                                                                                                
content-length: 238271986
```

Doing so again a few hours later:

```
$ curl --HEAD https://julialangnightlies-s3.julialang.org/bin/linux/x86_64/julia-latest-linux-x86_64.tar.gz 
HTTP/2 200 
x-amz-id-2: ScVqtq6it4zcR668VtNeP+Yx+HvvJ81Qd4VUOEBt+jpUBnUBScrjLJa+UtfnUnqH8y825C3eOS4=
x-amz-request-id: T1NVQN7DY60FV42R
last-modified: Thu, 25 Jan 2024 16:48:58 GMT
x-amz-expiration: expiry-date="Tue, 26 Mar 2024 00:00:00 GMT", rule-id="Cyberduck-u1YrSIk1"
etag: "78696eb7f7cc00c4e8c02424977b7103-29"
x-amz-server-side-encryption: AES256
content-type: application/x-tar
server: AmazonS3
accept-ranges: bytes
age: 8
date: Thu, 25 Jan 2024 18:22:36 GMT
via: 1.1 varnish
x-served-by: cache-bfi-kbfi7400093-BFI
x-cache: MISS
x-cache-hits: 0
x-timer: S1706206947.461058,VS0,VE8579
content-length: 238311991
```

Here, either `etag` or `last-modified` are reasonable things to check.  I usually use `last-modified`, because you can easily check the timestamp on the local machine to see if the archive you downloaded last time is older than that `last-modified` timestamp.

**Comment by davidanthoff** [comment]
Ah, great, that looks like something that could definitely work!

**Pull request merged**
