### PR TITLE
fix `is_juliaup_installed` for invalid path

### PR DESCRIPTION
**Pull request by t-bltg**
This PR:

- fixes https://github.com/JuliaLang/juliaup/issues/879;
- prints the Juliaup configuration file, if existing;
- ~~changes the `--add_to_path` description (`juliainstaller --help`) to match the command line argument `--add-to-path` (underscore -> dash)~~.

### CODE REVIEW

**Comment by t-bltg** [comment]
@davidanthoff, bump ?

**Review by StefanKarpinski — COMMENTED** [review]
I am not a Rust programmer but this looks reasonable to me. If no feedback in a week, I will merge.

**Comment by davidanthoff** [comment]
Hm, I'm not sure this is a good idea. If the user has a script `juliaup` on the `PATH` then things are really broken already, and I'm almost thinking we should just abort install at that point. What would be good is a better error message, for example something like "Your system has a broken `juliaup` command on the `PATH`, please first remove that" or something along those lines.

Could you move the unrelated typo fix to a different PR? Thanks!

**Comment by t-bltg** [comment]
> If the user has a script juliaup on the PATH then things are really broken already, and I'm almost thinking we should just abort install at that point

Exactly. Currently, `juliaup` returns a false positive as exposed in https://github.com/JuliaLang/juliaup/issues/879, and is thus a bug. This PR corrects this behaviour.

**Comment by t-bltg** [comment]
> Could you move the unrelated typo fix to a different PR?

Done in https://github.com/JuliaLang/juliaup/pull/916.

**Review by davidanthoff — APPROVED** [review]

**Pull request merged**
