### PR TITLE
Handle signals in julialauncher

### LINKED ISSUE #117: Figure out what the launcher should return if Julia was signal terminated
https://github.com/JuliaLang/juliaup/blob/60ccca7a7d2df94765c07a85da9115dbe2f37804/src/bin/julialauncher.rs#L228-L228

### PR DESCRIPTION
**Pull request by davidanthoff**
Fixes #117. Maybe.

@maleadt does this look like it might be doing what you think it should be doing?

### CODE REVIEW

**Comment by maleadt** [comment]
I think so, yes. Thanks!

I'm not familiar with Rust, but you might additionally need to disable the Rust exception handler (if any). For example, Julia registers a function that prints a backtrace on segfault. If Rust does too, the `raise` here would generate a Rust backtrace, which would be confusing to users. Disabling this involves calling the `signal` or `sigaction` functions.

**Comment by staticfloat** [comment]
This looks good to me, and it appears that at least by default, rust does not print out anything on receiving signals on Linux:

```
$ cat src/main.rs 
use nix;
fn main() {
    println!("About to raise:");
    nix::sys::signal::raise(nix::sys::signal::SIGTERM);
    println!("Already raised?:");
}
```

```
$ cargo run
   Compiling sigs v0.1.0 (/tmp/tmp.OYOflS5M20/sigs)
warning: unused `Result` that must be used
 --> src/main.rs:4:5
  |
4 |     nix::sys::signal::raise(nix::sys::signal::SIGTERM);
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_must_use)]` on by default
  = note: this `Result` may be an `Err` variant, which should be handled

warning: `sigs` (bin "sigs") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target/debug/sigs`
About to raise:
Terminated
```

I tried with a bunch of different signals like `SIGTERM`, `SIGINT`, `SIGABRT`, etc...

**Review by staticfloat — APPROVED** [review]

**Comment by davidanthoff** [comment]
@maleadt I pushed a build that includes this PR to the releasepreview channel (https://github.com/JuliaLang/juliaup/wiki/Trying-a-release-candidate). Could you try that build with your original repo case, whether things now work in the way you would expect them to work?

**Comment by maleadt** [comment]
Looks like the `raise` in Rust doesn't work well with all signals?

`SIGTRAP` works
```
❯ julia -e '@show run(ignorestatus(`julia -e "ccall(:raise, Cint, (Cint,), 5)"`))'
Process(`julia wip.jl 5`, ProcessSignaled(5))
```

`SIGSEGV` is skipped
```
❯ julia -e '@show run(ignorestatus(`julia -e "ccall(:raise, Cint, (Cint,), 11)"`))'
Error: Maybe we should never reach this?
Process(`julia wip.jl 11`, ProcessExited(1))
```

Works directly:

```
❯ julia -e '@show run(ignorestatus(`/path/to/julia -e "ccall(:raise, Cint, (Cint,), 11)"`))'
Process(`/path/to/julia wip.jl 11`, ProcessSignaled(11))
```

@staticfloat Did you check if the process correctly signalled when exiting?

**Comment by staticfloat** [comment]
I noticed that `SIGTERM`, `SIGABRT` and `SIGINT` worked as expected; but I agree, it looks like `SIGSEGV` is not working as expected.

It turns out that `rust` has special handlers for `SIGSEGV` and `SIGBUS`: https://github.com/rust-lang/rust/blob/984eab57f708e62c09b3d708033fe620130b5f39/library/std/src/sys/unix/stack_overflow.rs#L60-L80.  They handle it once, then [unregister themselves](https://github.com/rust-lang/rust/blob/8ac1525e091d3db28e67adcbbd6db1e1deaa37fb/src/libstd/sys/unix/stack_overflow.rs#L108-L111).  So what do we do?  We just `raise()` twice.  ;)

```
$ cat src/main.rs 
use nix;
fn main() {
    println!("About to raise:");
    let sig = nix::sys::signal::SIGABRT;
    nix::sys::signal::raise(sig);
    println!("Raising again:");
    nix::sys::signal::raise(sig);
    println!("Already raised?:");
}
```

```
$ cargo run
   Compiling sigs v0.1.0 (/tmp/tmp.cGeqidX1Sv/sigs)
warning: unused `Result` that must be used
 --> src/main.rs:6:5
  |
6 |     nix::sys::signal::raise(sig);
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_must_use)]` on by default
  = note: this `Result` may be an `Err` variant, which should be handled

warning: unused `Result` that must be used
 --> src/main.rs:8:5
  |
8 |     nix::sys::signal::raise(sig);
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this `Result` may be an `Err` variant, which should be handled

warning: `sigs` (bin "sigs") generated 2 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `target/debug/sigs`
About to raise:
Raising again:
Segmentation fault
```

I tested this and it works with `SIGHUP`, `SIGINT`, `SIGQUIT`, `SIGILL`, `SIGTRAP`, `SIGABRT`, `SIGBUS`, `SIGFPE`, `SIGKILL`, `SIGUSR1`, `SIGSEGV`, `SIGUSR2`, `SIGPIPE` (does not kill the process!), `SIGALRM`, and `SIGTERM`.

**Comment by davidanthoff** [comment]
Ah, excellent, I think https://github.com/JuliaLang/juliaup/pull/527 should implement that strategy. I'll ping here once I have a new build out for testing.

**Comment by davidanthoff** [comment]
I pushed a new build to the releasepreview channel, `juliaup -V` should show 1.8.14 for this one. @maleadt could you try again with that one? Thanks.

**Pull request merged**
