### PR TITLE
Fixed typo `uopdate`

### PR DESCRIPTION
**Pull request by shayandavoodii**
Found this typo an reported it [here](https://github.com/JuliaLang/juliaup/issues/535#issue-1510343156).
Fixes https://github.com/JuliaLang/juliaup/issues/535 and closes https://github.com/JuliaLang/juliaup/pull/537

### CODE REVIEW

**Comment by LilithHafner** [comment]
Lovely! This looks good to me. You can add "closing keywords" to the first post in this thread to automatically close issues and pull requests on merge. For example "Fixes #535 and closes #537" would automatically close both #535 and #537 when this PR merges. That way anyone who sees that issue or pull request will see that it was closed because this PR merged.

**Comment by LilithHafner** [comment]
Thank @shayandavoodii you for your contribution!

**Comment by shayandavoodii** [comment]
> 

@LilithHafner, Thank you for all of these. It was my first experience, so excuse me if it went slow or needed explanation and got energy from you. I will make sure to come across better next time.

**Comment by LilithHafner** [comment]
This was remarkably fast for a first contribution; if I recall correctly, my first took several days :)

**Comment by shayandavoodii** [comment]
Thank you. Thanks for these kind words.

**Comment by davidanthoff** [comment]
Hurray, many thanks :)

**Comment by shayandavoodii** [comment]
> Hurray, many thanks :)

Thank you for these great works. <B

**Pull request merged**
