### PR TITLE
If nightly or pr check is going slowly inform user

### PR DESCRIPTION
**Pull request by IanButterworth**
I just happened to hit this in the wild:

Screenshot 2024-11-03 at 9 53 05 AM

Helps explain https://github.com/JuliaLang/juliaup/issues/1096 to the user

### CODE REVIEW

**Comment by IanButterworth** [comment]
weird.. the formatter suggested removing imports that broke the code..

**Comment by IanButterworth** [comment]
Bump

**Comment by davidanthoff** [comment]
I guess we can merge this for now, but somehow this makes me think that we maybe should just adopt `tokio` for the `juliaup` binary and then do this using async features... For example, the Windows download API is already completely async, so it really shouldn't be necessary to use extra threads to do something like that, and `reqwest` also has a fully async API, so same story.

Plus, we already have some places where we for example start a number of parallel downloads via async, but those things could presumably also be simplified if we had a proper async runtime.

**Comment by IanButterworth** [comment]
Merge?

**Comment by IanButterworth** [comment]
Bump for having this released.

**Comment by IanButterworth** [comment]
@davidanthoff I will look into making a new release at the end of the week. Let me know if I shouldn't. Thanks.

**Pull request merged**
