### PR TITLE
Add native TLS and native certs features

### PR DESCRIPTION
**Pull request by tedbyron**
- Added two features for native TLS - `tls-native` and native certs - `native-certs` (feature can't be called `native-tls` because that is crate name)
- New optional dependency `native-tls` added; only linked when feature flag `tls-native` is on
- **Note**: `rustls` is always a dependency of `ureq`, even when using `native-tls`.

Valid configurations now:

| features | tls | certs |
|-|-|-|
| (default) | `rustls` | `webpki-roots` |
| `native-certs` | `rustls` | `rustls-native-certs` |
| `tls-native` | `native-tls` | `webpki-roots` |
| `tls-native, native-certs` | `native-tls` | `rustls-native-certs` |

Tested on `x86_64-apple-darwin`
<details>
  <summary>test native TLS & certs <code>cargo t --features 'tls-native native-certs'</code></summary>
  <pre><code>
   Compiling juliaup v1.5.37-alpha.0 (/Users/ted/juliaup)
    Finished test [unoptimized + debuginfo] target(s) in 1.72s
     Running unittests (target/debug/deps/juliaup-22cb1e9ed71bfb49)

running 1 test
test utils::tests::test_parse_versionstring ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/juliainstaller-aa3db24a0945e160)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/julialauncher-577759c03065df8c)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/juliaup-b04239b11e46832c)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/command_add.rs (target/debug/deps/command_add-5a537c074f3802d8)

running 1 test
test command_add has been running for over 60 seconds
test command_add ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 66.30s

     Running tests/command_default.rs (target/debug/deps/command_default-6be9cc542f71ec2e)

running 1 test
test command_default has been running for over 60 seconds
test command_default ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 70.30s

     Running tests/command_initial_setup_from_launcher_test.rs (target/debug/deps/command_initial_setup_from_launcher_test-54f1a272b1aa190f)

running 1 test
test command_initial_setup has been running for over 60 seconds
test command_initial_setup ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 64.81s

     Running tests/command_remove.rs (target/debug/deps/command_remove-04c423134f3330d7)

running 1 test
test command_remove has been running for over 60 seconds
test command_remove ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 123.96s

     Running tests/command_status_test.rs (target/debug/deps/command_status_test-c39ae9f1cba5e9b4)

running 1 test
test command_status ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

     Running tests/command_update.rs (target/debug/deps/command_update-2ddbca89558d3daf)

running 1 test
test command_update ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.09s

   Doc-tests juliaup

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
  </code></pre>
</details>

<details>
  <summary>test native TLS <code>cargo t --features 'tls-native'</code></summary>

  <pre><code>
   Compiling juliaup v1.5.37-alpha.0 (/Users/ted/juliaup)
    Finished test [unoptimized + debuginfo] target(s) in 3.33s
     Running unittests (target/debug/deps/juliaup-ef93399db8ff46cf)

running 1 test
test utils::tests::test_parse_versionstring ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/juliainstaller-75b312511119b2cb)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/julialauncher-e5ed85cc88935322)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/juliaup-05da9fb3f0c9eb42)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/command_add.rs (target/debug/deps/command_add-6397eded339fc3f8)

running 1 test
test command_add has been running for over 60 seconds
test command_add ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 62.42s

     Running tests/command_default.rs (target/debug/deps/command_default-d8316db2eba9ed36)

running 1 test
test command_default has been running for over 60 seconds
test command_default ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 60.60s

     Running tests/command_initial_setup_from_launcher_test.rs (target/debug/deps/command_initial_setup_from_launcher_test-e438297376bb420b)

running 1 test
test command_initial_setup ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 59.27s

     Running tests/command_remove.rs (target/debug/deps/command_remove-726038e702474dcd)

running 1 test
test command_remove has been running for over 60 seconds
test command_remove ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 115.26s

     Running tests/command_status_test.rs (target/debug/deps/command_status_test-0613d247dfc1f421)

running 1 test
test command_status ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s

     Running tests/command_update.rs (target/debug/deps/command_update-f53fceefbb1f6ce5)

running 1 test
test command_update ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.09s

   Doc-tests juliaup

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
  </code></pre>
</details>

<details>
  <summary>test native certs <code>cargo t --features 'native-certs'</code></summary>
  <pre><code>
   Compiling juliaup v1.5.37-alpha.0 (/Users/ted/juliaup)
    Finished test [unoptimized + debuginfo] target(s) in 5.71s
     Running unittests (target/debug/deps/juliaup-8152b68275ace826)

running 1 test
test utils::tests::test_parse_versionstring ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/juliainstaller-ff03c7686c38c746)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/julialauncher-df00a3fdb632b3df)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/juliaup-873a883cd8e6c2cc)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/command_add.rs (target/debug/deps/command_add-326b9206e18a9e0a)

running 1 test
test command_add has been running for over 60 seconds
test command_add ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 68.69s

     Running tests/command_default.rs (target/debug/deps/command_default-ce94185a5ee6bd2f)

running 1 test
test command_default has been running for over 60 seconds
test command_default ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 68.91s

     Running tests/command_initial_setup_from_launcher_test.rs (target/debug/deps/command_initial_setup_from_launcher_test-196f7051f81f7de9)

running 1 test
test command_initial_setup has been running for over 60 seconds
test command_initial_setup ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 64.47s

     Running tests/command_remove.rs (target/debug/deps/command_remove-d3789b9c8d547ecf)

running 1 test
test command_remove has been running for over 60 seconds
test command_remove ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 122.21s

     Running tests/command_status_test.rs (target/debug/deps/command_status_test-085386f444adbce5)

running 1 test
test command_status ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

     Running tests/command_update.rs (target/debug/deps/command_update-f339ff92afe544c3)

running 1 test
test command_update ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.09s

   Doc-tests juliaup

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
  </code></pre>
</details>

```sh
└ > cargo r --features 'tls-native native-certs' add beta
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/juliaup add beta`
Installing Julia 1.7.2+0 (x64).

└ > cargo r --features 'tls-native native-certs' status
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/juliaup status`
 Default  Channel  Version      Update
---------------------------------------
       *  beta     1.7.2+0~x64
```

May need some help adding it to CI, not too familiar with github actions and rust features.

### CODE REVIEW

**Comment by tedbyron** [comment]
Let me know if I should change `default-features` to use `native-certs`

**Comment by davidanthoff** [comment]
@tedbyron Thanks so much for this PR! I simplified it a bit so that it really only has the minimal diff required to get this going. I also configured things to always use `tls-native` and `native-certs` by default, I think if that works we should just use that always.

If you want to take a final look, please do, I hope to merge this soon and then test it in the wild for a bit.

**Comment by davidanthoff** [comment]
Ok, I for now removed the config options, because I ran into some problems on Unix where the `native-tls` somehow interacts with OpenSSL (I think?) and it was all too involved. So, for now this will use `native-tls` on Win and Mac, and `native-cert` on Unix.

**Comment by davidanthoff** [comment]
Ok, I don't understand why these builds are failing... There must be some stupid configuration error, but I can't figure it out. If anyone wants to help, please do :)

**Pull request merged**
